#!/usr/bin/perl
use warnings;
use strict;
use YAML::XS qw(LoadFile);
use DBI;
use File::Path qw(make_path);
use Spreadsheet::WriteExcel;
use FindBin qw($Bin);
use lib "$FindBin::Bin/../lib";
use Format;
use Math;
use Analyse::RequetesCourantes;
use Traitement_resultats::FonctionsXls;

# ==============================================================================
# Parametres
# ==============================================================================

# On récupère l'id du projet a analyser
my $id_analyse = shift @ARGV || die('Vous devez passer l\'id d\'une analyse en paramètre');

# On récupère un hash de config
my $config = LoadFile($FindBin::Bin . '/../config.yml');

# On défini les identifiants pour la bdd
my $db_host = $config->{'db_host'};
my $db_user = $config->{'db_user'};
my $db_pass = $config->{'db_pass'};
my $db_name = $config->{'db_name'};

# Paramètres de sélection pour les résulats
my $seuil_epissage = $config->{'simple'}{'excel'}{'seuil_epissage'};
my $seuil_pval = $config->{'simple'}{'excel'}{'seuil_pval'};
my $seuil_fiabilite_fcGene = $config->{'simple'}{'excel'}{'seuil_fc_gene'};

# Répertoire de sortie 
my $dir_xls = $config->{'dir_xls'};

# ==============================================================================
# Connection à elexir et préparation des requetes
# ==============================================================================

my $dbh = DBI->connect(
	"DBI:mysql:" . $db_name . ":" . $db_host,
	$db_user,
	$db_pass
);

# On selectionne les infos de l'analyse
my $select_infos_analyse_sth = $dbh->prepare(
	"SELECT a.id_project, a.name, p.organism, p.type as type_chips,
	a.version, a.type
	FROM projects AS p, analyses AS a
	WHERE a.id_project = p.id
	AND a.id = ?"
);

# ==============================================================================
# On récupère les infos de l'analyse
# ==============================================================================

$select_infos_analyse_sth->execute($id_analyse);

my $infos_analyse = $select_infos_analyse_sth->fetchrow_hashref;

die('L\'id de l\'analyse n\'est pas valide.') if(!$infos_analyse);

# Message d'erreur si c'est pas le bon script pour le bon type d'analyse
if($infos_analyse->{'type'} ne 'simple'){

	die('Le script simple ne fonctionne que sur les analyses simples :o)');

}

# ==============================================================================
# On récupère les infos dont on a besoin selon les infos de l'analyse
# ==============================================================================

# On récupère les infos de la bdd
my $id_projet = $infos_analyse->{"id_project"};
my $type_chips = $infos_analyse->{'type_chips'};
my $version = $infos_analyse->{'version'};
my $orga = $infos_analyse->{'organism'};
my $name = $infos_analyse->{'name'};
my $paire = $infos_analyse->{'paired'};

# on crée les variables du script qui déendent de l'analyse
my $table_genes = $config->{'table_genes'}{$version}{$orga};
my $table_entites = $config->{'table_entites'}{$version}{$orga};
my $table_trans = get_table_transcription($id_projet, $id_analyse);
my $table_splicing = get_table_splicing($id_projet, $id_analyse);
my $dir_sortie = $dir_xls . '/' . $id_projet . '/' . $id_analyse;
my $fichier_sortie = $dir_sortie . '/' . $name . '_epissage.xls';

# On crée les dossier
make_path($dir_sortie);

# ==============================================================================
# On se connecte a fasterdb
# ==============================================================================

my $select_entites_nofdr_sth = $dbh->prepare(
	"SELECT e.*, g.epi_fc, g.epi_pval, g.epi_nb_sondes, g.epi_nb_exons
	FROM $table_trans AS g, $table_splicing AS e
	WHERE g.id_gene = e.id_gene AND is_robust = 1"
);

my $select_entites_fdr_sth = $dbh->prepare(
	"SELECT e.*, g.epi_fc, g.epi_pval, g.epi_nb_sondes, g.epi_nb_exons,
	e.SI_adjp AS SI_pval, e.SIsd_adjp AS SIsd_pval, e.psi_adjp AS psi_pval
	FROM $table_trans AS g, $table_splicing AS e
	WHERE g.id_gene = e.id_gene AND is_robust = 1"
);

my $select_infos_gene_sth = $dbh->prepare(
	"SELECT * FROM $table_genes WHERE id_fasterdb = ?"
);

my $select_infos_entite_sth = $dbh->prepare(
	"SELECT type, exon_pos, start_sur_gene, end_sur_gene
	FROM $table_entites
	WHERE id = ?"
);

# ==============================================================================
# Initialisation fichier excel
# ==============================================================================

# Fichier
my $xlsh			= Spreadsheet::WriteExcel->new($fichier_sortie);

# Feuilles
my $f_resume			= $xlsh->add_worksheet('Parametres et entites analysees');
my $f_epissage_no_fdr		= $xlsh->add_worksheet('NO FDR');
my $f_epissage_fdr		= $xlsh->add_worksheet('FDR');

# Couleurs
my $couleur_entete		= $xlsh->set_custom_color(39, 189, 189, 189);

# Formats
my $format_resume_titre		= $xlsh->add_format(color => 'black', bold => 1, center_across => 1);
my $format_resume_intermediaire	= $xlsh->add_format(color => 'black', italic => 1, center_across => 1);
my $format_resume_cell		= $xlsh->add_format(color => 'black', bold => 0, center_across => 1);
my $format_merge_entete		= $xlsh->add_format(color => 'black', bold => 1, bg_color => $couleur_entete, border => 2, border_color => 'black', center_across => 1);
my $format_entete		= $xlsh->add_format(color => 'black', bold => 1, bg_color => $couleur_entete, border => 2, border_color => 'black', center_across => 1);
my $format_cell			= $xlsh->add_format(color => 'black', border => 1, border_color => 'black', center_across => 1);
my $format_cell_mauv_fc		= $xlsh->add_format(color => 'red', border => 1, border_color => 'black', center_across => 1);
my $format_cell_no_center	= $xlsh->add_format(color => 'black', bold => 0);

# ==============================================================================
# Feuille résumé
# ==============================================================================

# Infos de base
$f_resume->write(0, 0, date(), $format_cell_no_center);
$f_resume->write(2, 0, "Parametres utilises", $format_resume_titre);
$f_resume->write(3, 0, "Seuil fold", $format_resume_titre);
$f_resume->write(3, 1, round($seuil_epissage, 2), $format_resume_titre);
$f_resume->write(4, 0, "Seuil p-value", $format_resume_titre);
$f_resume->write(4, 1, $seuil_pval, $format_resume_titre);

# ==============================================================================
# On ajoute les entités dans les feuilles
# ==============================================================================

# Fonction pour formatter le fold
sub format_fold{

	my($fold) = @_;

	return ($fold >= 1) ? $fold : 1/$fold;

}

my @entites = ();

# On selectionne les entites no fdr
$select_entites_nofdr_sth->execute;
@entites = @{$select_entites_nofdr_sth->fetchall_arrayref({})};
$select_entites_nofdr_sth->finish;

my($nb_nofdr_up, $nb_nofdr_down) = write_list($f_epissage_no_fdr, @entites);

# On selectionne les entites fdr
$select_entites_fdr_sth->execute;
@entites = @{$select_entites_fdr_sth->fetchall_arrayref({})};
$select_entites_fdr_sth->finish;

my($nb_fdr_up, $nb_fdr_down) = write_list($f_epissage_no_fdr, @entites);

# ==============================================================================
# Fonction pour remplir la feuille
# ==============================================================================

sub write_list{

	my($f, @entites) = @_;

	my $num_ligne = 2;	# On commence par la troisieme ligne (les deux
				# premieres sont les entetes)
	my $nb_gene = 0;
	my $gene_id_prec = 0;
	my $nb_ups = 0;
	my $nb_downs = 0;

	# On défini les entete groupées
	$f->merge_range(0, 0, 0, 3, 'Infos analyse', $format_merge_entete);
	$f->merge_range(0, 4, 0, 11, 'Infos gene', $format_merge_entete);
	$f->merge_range(0, 12, 0, 15, 'Infos entite', $format_merge_entete);
	$f->merge_range(0, 16, 0, 18, 'Reg gene', $format_merge_entete);
	$f->merge_range(0, 19, 0, 21, 'Reg SI', $format_merge_entete);
	$f->merge_range(0, 22, 0, 24, 'Reg SIsd', $format_merge_entete);
	$f->merge_range(0, 25, 0, 32, 'Reg Psi', $format_merge_entete);

	# On défini les entetes de chaque colonnes
	my @entetes = (
		'Gene',
		'SI',
		'SIsd',
		'Psi',
		# Infos du gène
		'Fasterdb id',
		'Source id',
		'Link Elexir',
		'Symbol',
		'Description',
		'Chr Position',
		'Nb probes',
		'Nb exons',
		# Infos entité
		'AS Event Type',
		'Exon position',
		'Nb probes',
		'AS Event Sequence',
		# Reg gène
		'Regulation',
		'FC',
		'Pvalue',
		# Reg SI
		'Regulation',
		'Med SI',
		'Pvalue',
		# Reg SIsd
		'Regulation',
		'Med SIsd',
		'Pvalue',
		# Reg psi
		'Regulation',
		'Med Psi Control',
		'sd Med Psi Control',
		'Med Psi Test',
		'sd Med Psi Test',
		'Med Psi FC',
		'sd Med Psi FC',
		'Pvalue'
	);

	for(my $j = 0; $j < @entetes; $j++){

		$f->write(1, $j, $entetes[$j], $format_entete);

	}

	# Fonction qui retourne 1 si l'entité est valide pour les trois types
	sub commun{

		my($entite) = @_;

		return(
			($entite->{'SI'} >= $seuil_epissage and ($entite->{'SI_pval'} <= $seuil_pval))
			and
			($entite->{'SIsd'} >= $seuil_epissage and (!$paire or ($entite->{'SIsd_pval'} <= $seuil_pval)))
			and
			($entite->{'psi_fc'} >= $seuil_epissage and (!$paire or ($entite->{'psi_pval'} <= $seuil_pval)))
		);

	}

	# On classe les entites
	@entites = sort {
		# On classe déjà les communs en premier
		commun($b) <=> commun($a)
#		||
		# Ensuite par FC gène fiable
#		(format_fold($b->{'epi_fc'}) <= $seuil_fiabilite_fcGene)
#			<=>
#		(format_fold($a->{'epi_fc'}) <= $seuil_fiabilite_fcGene)
#		||
		# Ensuite par SI up ou down
#		($b->{'SI'} >= 1) <=> ($a->{'SI'} >= 1)
#		||
		# Ensuite par SI décroissant
#		format_fold($b->{'SI'}) <=> format_fold($a->{'SI'})
	} @entites;

	# Pour chaque entité
	foreach my $entite (@entites){

		# On test si il y en a au moins un
		my $SI_ok = ($entite->{'SI'} >= $seuil_epissage and ($entite->{'SI_pval'} <= $seuil_pval));
		my $SIsd_ok = ($entite->{'SIsd'} >= $seuil_epissage and (!$paire or ($entite->{'SIsd_pval'} <= $seuil_pval)));
		my $psi_ok = ($entite->{'psi_fc'} >= $seuil_epissage and (!$paire or ($entite->{'psi_pval'} <= $seuil_pval)));

		# On zappe si il n'y en a pas au moins un
		next if(!$SI_ok and !$SIsd_ok and !$psi_ok);

		# On récupère les infos du gène
		$select_infos_gene_sth->execute($entite->{'id_gene'});
		my $infos_gene = $select_infos_gene_sth->fetchrow_hashref;
		$select_infos_gene_sth->finish;

		# On récupère les infos de l'entité
		$select_infos_entite_sth->execute($entite->{'id_entite'});
		my $infos_entite = $select_infos_entite_sth->fetchrow_hashref;
		$select_infos_entite_sth->finish;

		# On met a jour le numéro du gène
		if($infos_gene->{'id_fasterdb'} != $gene_id_prec){

			$nb_gene++;

			$gene_id_prec = $infos_gene->{'id_fasterdb'};

		}

		# On compte les up et les down
		($entite->{'SI'} >= 1) ? $nb_ups++ : $nb_downs++;

		my $pos_chrom =
			$infos_gene->{'chromosome'} .
			':' . $infos_gene->{'start_sur_chromosome'} .
			'-' . $infos_gene->{'end_sur_chromosome'} .
			':' . $infos_gene->{'strand'};

		my $prefix_pos = ($infos_entite->{'type'} eq 'intron-retention')
			? 'i' : 'e' ;

		my $pos_entite =
			$prefix_pos . $entite->{'exon_pos'} .
			':' . $infos_entite->{'start_sur_gene'} .
			'-' . $infos_entite->{'end_sur_gene'};

		my $reg_gene = ($entite->{'epi_fc'} >= 1) ? 'up' : 'down';
		my $reg_SI = ($entite->{'SI'} >= 1) ? 'up' : 'down';
		my $reg_SIsd = ($entite->{'SIsd'} >= 1) ? 'up' : 'down';
		my $reg_psi = ($entite->{'psi_fc'} >= 1) ? 'up' : 'down';

		my $format = (format_fold($entite->{'epi_fc'}) <= $seuil_fiabilite_fcGene)
			? $format_cell
			: $format_cell_mauv_fc;

		# On crée le tableau de data
		my @data = (
			$nb_gene,
			($SI_ok) ? 'X' : '',
			($SIsd_ok) ? 'X' : '',
			($psi_ok) ? 'X' : '',
			# Infos du gène
			$infos_gene->{'id_fasterdb'},
			$infos_gene->{'id_source'},
			'blah',
			$infos_gene->{'symbol'},
			$infos_gene->{'description'},
			$pos_chrom,
			$entite->{'epi_nb_sondes'},
			$entite->{'epi_nb_exons'},
			# Infos entité
			$infos_entite->{'type'},
			$pos_entite,
			$entite->{'nb_sondes'},
			'seq',
			# Regulation gène
			$reg_gene,
			format_fold($entite->{'epi_fc'}),
			$entite->{'epi_pval'},
			# Algo SI
			$reg_SI,
			format_fold($entite->{'SI'}),
			$entite->{'SI_pval'},
			# Algo SIsd
			$reg_SIsd,
			format_fold($entite->{'SIsd'}),
			$entite->{'SIsd_pval'},
			# Algo psi
			$reg_psi,
			$entite->{'psi_control'},
			$entite->{'psi_sd_control'},
			$entite->{'psi_test'},
			$entite->{'psi_sd_test'},
			$entite->{'psi_fc'},
			$entite->{'psi_sd_fc'},
			$entite->{'psi_pval'}
		);

		# On affiche les data
		for(my $j = 0; $j < @data; $j++){

			# $i + 1 parce que la premiere ligne est l'entete
			$f->write($num_ligne, $j, $data[$j], $format);

		}

		$num_ligne++;

	}

}
