# connection aux base de données
db_host: localhost
db_user: elexir2
db_pass: pandas
db_name: elexir2

# Fichier de logs pour le daemon
log_file: /data/logs/elexir2.log

# Nombre de threads max que le demon peut lancer en même temps
nb_threads: 2

# Repertoires de données
dir_cel: /data/elexir/celfiles
dir_qc: /data/elexir/reports
dir_xls: /data/elexir/reports
dir_web: plateforme2

# Description des fichiers d'annotations
annotations:
  exon:
    human:
      pgf: /data/elexir/annotations/HuEx-1_0-st-v2.r2/HuEx-1_0-st-v2.r2.pgf
      clf: /data/elexir/annotations/HuEx-1_0-st-v2.r2/HuEx-1_0-st-v2.r2.clf
      bgp: /data/elexir/annotations/HuEx-1_0-st-v2.r2/HuEx-1_0-st-v2.r2.antigenomic.bgp
      qcc: /data/elexir/annotations/HuEx-1_0-st-v2.r2/HuEx-1_0-st-v2.r2.qcc
      mps: /data/elexir/annotations/HuEx-1_0-st-v2.r2.dt1.hg18.ps/HuEx-1_0-st-v2.r2.dt1.hg18.core.mps
    mouse:
      pgf: /data/elexir/annotations/MoEx-1_0-st-v1.r2/MoEx-1_0-st-v1.r2.pgf
      clf: /data/elexir/annotations/MoEx-1_0-st-v1.r2/MoEx-1_0-st-v1.r2.clf
      bgp: /data/elexir/annotations/MoEx-1_0-st-v1.r2/MoEx-1_0-st-v1.r2.antigenomic.bgp
      qcc: /data/elexir/annotations/MoEx-1_0-st-v1.r2/MoEx-1_0-st-v1.r2.qcc
      mps: /data/elexir/annotations/MoEx-1_0-st-v1.r2.dt1.mm9.ps/MoEx-1_0-st-v1.r2.dt1.mm9.core.mps
  ggh:
    human:
      pgf: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.pgf
      pgf_correction: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1_gc.pgf
      clf: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.clf
      bgp: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.antigenomic.bgp
      qcc: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.qcc
      mps: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.TC.mps

# Noms de fasterdb selon qu'on est sur la version 1 ou 2
db_name_fasterdb:
  fdb1:
    human: fasterdb_humain
    mouse: fasterdb_souris
  fdb2:
    human: fasterdb2_humain
    mouse: fasterdb2_souris

# Tables selon le type de puces, la version de fasterdb et l'organisme
table_genes:
  fdb1:
    human: humain_fdb1_genes
    mouse: souris_fdb1_genes
  fdb2:
    human: humain_fdb2_genes

table_entites:
  fdb1:
    human: humain_fdb1_entites
    mouse: souris_fdb1_entites
  fdb2:
    human: humain_fdb2_entites
    mouse: souris_fdb2_entites

table_entites_a_priori:
  fdb1:
    human: humain_fdb1_entites_a_priori

table_ase:
  fdb1:
    human: humain_fdb1_ase
    mouse: souris_fdb1_ase
  fdb2:
    human: humain_fdb2_ase
    mouse: souris_fdb2_ase

table_sondes:
  exon:
    fdb1:
      human: humain_huex_fdb1_probes_status
      mouse: souris_moex_fdb1_probes_status
    fdb2:
      human: humain_huex_fdb2_probes_status
      mouse: souris_moex_fdb2_probes_status
  ggh:
    fdb1:
      human: humain_ggh_fdb1_probes_status
    fdb2:
      human: humain_ggh_fdb2_probes_status

table_jonctions_exons:
  ggh:
    fdb1:
      human: humain_fdb1_jonctions_entites_a_priori
    fdb2:
      human: humain_fdb2_jonctions_entites_a_priori

# Paramètres pour les algos
qc:
  algo: rma

correction:
  algo: rma-bg,quant-norm,pm-only

simple:
  gc_max: 17
  nb_occ_max: 1
  seuil_dabg: 0.05
  nb_sondes_min_gene: 6
  nb_sondes_min_entite: 3
  seuil_si_robust: 1.1 # En base 10 !
  excel:
    seuil_trans: 1.2 # En base 10 !
    seuil_epissage: 1.45 # En base 10 !
    seuil_pval: 0.05
    seuil_fdr: 0.05
    seuil_fc_gene: 2

compose:
  gc_max: 17
  nb_occ_max: 1
  seuil_dabg: 0.05
  nb_sondes_min_gene: 6
  nb_sondes_min_entite: 3
  seuil_si_robust: 1.1 # En base 10 !
  excel:
    seuil_trans_simple: 1.45 # En base 10 !
    seuil_trans_j_vs_o: 1.2 # En base 10 !
    seuil_epissage_simple: 1.45 # En base 10 !
    seuil_epissage_j_vs_o: 1.2 # En base 10 !
    seuil_pval: 0.05
    seuil_fc_gene: 2

jonction:
  gc_max: 17
  nb_occ_max: 1
  seuil_dabg: 0.05
  nb_sondes_min_entite: 3
  excel:
    seuil_epissage: 1.45 # En base 10 !
    seuil_pval: 0.05
    seuil_fdr: 0.05

apriori:
  gc_max: 17
  nb_occ_max: 1
  seuil_dabg: 0.05
  nb_sondes_min_ase: 3
  nb_sondes_min_flanquants: 6
