# connection aux base de données
db_host: localhost
db_user: elexir2
db_pass: pandas
db_name: elexir2

db_name_fasterdb:
  human: fasterdb_humain
  mouse: fasterdb_souris

# Fichier de logs pour le daemon
log_file: /data/logs/elexir2.log

# Nombre de threads max que le demon peut lancer en même temps
nb_threads: 2

# Repertoires de données
dir_cel: /data/elexir/celfiles
dir_qc: /data/elexir/reports
dir_xls: /data/elexir/reports
dir_web: plateforme2

# Description des fichiers d'annotations
annotations:
  exon:
    human:
      pgf: /data/elexir/annotations/HuEx-1_0-st-v2.r2/HuEx-1_0-st-v2.r2.pgf
      clf: /data/elexir/annotations/HuEx-1_0-st-v2.r2/HuEx-1_0-st-v2.r2.clf
      bgp: /data/elexir/annotations/HuEx-1_0-st-v2.r2/HuEx-1_0-st-v2.r2.antigenomic.bgp
      qcc: /data/elexir/annotations/HuEx-1_0-st-v2.r2/HuEx-1_0-st-v2.r2.qcc
      mps: /data/elexir/annotations/HuEx-1_0-st-v2.r2.dt1.hg18.ps/HuEx-1_0-st-v2.r2.dt1.hg18.core.mps
    mouse:
      pgf: /data/elexir/annotations/MoEx-1_0-st-v1.r2/MoEx-1_0-st-v1.r2.pgf
      clf: /data/elexir/annotations/MoEx-1_0-st-v1.r2/MoEx-1_0-st-v1.r2.clf
      bgp: /data/elexir/annotations/MoEx-1_0-st-v1.r2/MoEx-1_0-st-v1.r2.antigenomic.bgp
      qcc: /data/elexir/annotations/MoEx-1_0-st-v1.r2/MoEx-1_0-st-v1.r2.qcc
      mps: /data/elexir/annotations/MoEx-1_0-st-v1.r2.dt1.mm9.ps/MoEx-1_0-st-v1.r2.dt1.mm9.core.mps
  ggh:
    human:
      pgf: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.pgf
      pgf_correction: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1_gc.pgf
      clf: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.clf
      bgp: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.antigenomic.bgp
      qcc: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.qcc
      mps: /data/elexir/annotations/hGlue_3_0_v1.R-JETTA_lib_annot_files/hGlue_3_0_v1.TC.mps

# Tables selon l'organisme
table_entites:
  human: humain_fdb1_entites
  mouse: souris_fdb1_entites

table_sondes:
  human:
    exon: humain_probes_status_fdb1_exon
    ggh: humain_probes_status_fdb1_ggh
  mouse:
    exon: souris_probes_status_fdb1_exon

table_prom:
  human: humain_prom
  mouse: souris_prom

table_polya:
  human: humain_polya
  mouse: souris_polya

# Paramètres pour les algos
qc:
  algo: rma

correction:
  algo: rma-bg,quant-norm,pm-only

simple:
  gc_max: 17
  nb_occ_max: 1
  seuil_dabg: 0.05
  seuil_si: 1.1 # En base 10 !

excel:
  seuil_transcription: 1.2 # En base 10 !
  seuil_epissage: 1.45 # En base 10 !
  seuil_pval: 0.05
  seuil_fc_gene: 2
