#!/usr/bin/python
# -*- coding: UTF-8 -*-
import os
import sys
import yaml
import threading
import time
import datetime
import MySQLdb
import subprocess

# ==============================================================================
# On définit des constantes
# ==============================================================================

# On récupère le répertoire de travail
wd = sys.path[0]

# On récupère la config
config = yaml.load(file(wd + '/config.yml', 'r'))

# Base de données
DBHOST = config['db_host']
DBUSER = config['db_user']
DBPASS = config['db_pass']
DBNAME = config['db_name']

# Nombre de threads autorisés en même temps
NBTHREADS = config['nb_threads']

# ==============================================================================
# Fonction retournant la date/heure actuelle
# ==============================================================================

def now():
	return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S");

# ==============================================================================
# Fonction thread 
# ==============================================================================

def do_job(wd, job, sema):

	id_job = job[0];

	weight = 0
	id_elem = ''
	algo = ''

	if(job[3] == 'qc'):
		id_elem = job[1]
		algo = 'qc'
		weight = 5
	if(job[3] == 'preprocessing'):
		id_elem = job[1]
		algo = 'correction'
		weight = 5
	if(job[3] == 'analysis'):
		id_elem = job[2]
		if(job[4] == 'simple'):
			algo = 'analyse_simple'
		if(job[4] == 'compose'):
			algo = 'analyse_compose'
		if(job[4] == 'jonction'):
			algo = 'analyse_jonction'
		weight = 1
	if(job[3] == 'excels'):
		id_elem = job[2]
		if(job[4] == 'simple'):
			algo = 'excels_simple'
		if(job[4] == 'compose'):
			algo = 'excels_compose'
		if(job[4] == 'jonction'):
			algo = 'excels_jonction'
		weight = 1

	# On se connecte a la bdd
	dbh = MySQLdb.connect(host = DBHOST, user = DBUSER, passwd = DBPASS, db = DBNAME)
	cursor = dbh.cursor()

	# Si on a pas d'element ou d'algo correspondant au job on le termine
	if(id_elem == '' or algo == ''):

		cursor.execute('UPDATE jobs SET status = %(status)s, start = %(date)s, end = %(date)s WHERE id = %(id)s', {'id':id_job, 'status':'done', 'date':now()})

	else:

		# On prend des sema proportionellement à ce que l'on fait :)
		sema.acquire()

		cursor.execute('UPDATE jobs SET status = %(status)s, start = %(date)s WHERE id = %(id)s', {'id':id_job, 'status':'processing', 'date':now()})

		log_file = open(config['log_file'], 'a')
		log_file.write(id_elem + ' ' + algo + ' ' + now())
		log_file.write("\n")

		subprocess.call(
			[wd + '/' + algo, str(id_elem)],
			stdout=log_file,
			stderr=subprocess.STDOUT,
		)

		log_file.write("\n")
		log_file.close();

		cursor.execute('UPDATE jobs SET status = %(status)s, end = %(date)s WHERE id = %(id)s', {'id':id_job, 'status':'done', 'date':now()})
		cursor.close
		dbh.close

		# On relache des sema
		sema.release()

# ==============================================================================
# Script / boucle infinie
# ==============================================================================

while(1):
	dbh = MySQLdb.connect(host = DBHOST, user = DBUSER, passwd = DBPASS, db = DBNAME)

	sema = threading.Semaphore(NBTHREADS);

	while(1):

		cursor = dbh.cursor()
		cursor.execute('SELECT j.id, j.id_project, j.id_analysis, j.type, a.type FROM jobs AS j LEFT JOIN analyses AS a ON a.id = j.id_analysis WHERE j.status = %(status)s', {'status':'starting'})
		jobs = cursor.fetchall()

		for job in jobs:
			cursor.execute('UPDATE jobs SET status = %(status)s WHERE id = %(id)s', {'id':job[0], 'status':'waiting'})
			thread = threading.Thread(target = do_job, args = (wd, job, sema))
			thread.start()
			print thread

		time.sleep(5)
