#! /bin/sh -e

dir=$(dirname $(readlink -f $0))

DAEMON="$dir/daemon" #ligne de commande du programme
DAEMON_OPT=""  #argument à utiliser par le programme
DAEMONUSER="pierre" #utilisateur du programme
DAEMON_NAME="daemon" #Nom du programme (doit être identique à l'exécutable)
DAEMON_DISPLAY_NAME="elexir2"

PATH="/sbin:/bin:/usr/sbin:/usr/bin" #Ne pas toucher

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

d_start () {
        log_daemon_msg "Starting system $DAEMON_DISPLAY_NAME Daemon"
	start-stop-daemon --background --name $DAEMON_NAME --start --quiet --user $DAEMONUSER --exec $DAEMON -- $DAEMON_OPT
        log_end_msg $?
}

d_stop () {
        log_daemon_msg "Stopping system $DAEMON_DISPLAY_NAME Daemon"
        start-stop-daemon --name $DAEMON_NAME --stop --retry 5 --quiet --name $DAEMON_NAME
	log_end_msg $?
}

case "$1" in

        start|stop)
                d_${1}
                ;;

        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;

        force-stop)
               d_stop
                killall -q $DAEMON_NAME || true
                sleep 2
                killall -q -9 $DAEMON_NAME || true
                ;;

        status)
                status_of_proc "$DAEMON_NAME" "$DAEMON" "system-wide $DAEMON_NAME" && exit 0 || exit $?
                ;;
        *)
                echo "Usage: /etc/init.d/$DAEMON_DISPLAY_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0
