#!/usr/bin/perl
use warnings;
use strict;

my $header = 0;

while(my $line = <>){

	chomp $line;

	# On vire les commentaires et le header
	next if($line =~ /^#/);

	if($header == 0){ $header = 1; next; }

	# On récupère les parties
	my @parts = split("\t", $line);

	# On vire les infos qu'on veut pas
	my $probeset_id = shift @parts;
	my $atom_id = shift @parts;
	my $probe_id = shift @parts;
	my $x = shift @parts;
	my $y = shift @parts;

	# Le reste c'est les intensités
	# ON MULTIPLIE PAR 10 000 !!
	# (=> histoire de stoquer un int et pas un float, moins lourd
	# 10 000 = 4 chiffres apres la virgule de précision, affymetrix fait 5
	# chiffres après la virgule, mais on veut stoquer en smallint (soit <
	# que 65 000 et des patates)
	my @rows = map { 10000 * $_ } @parts;

	# On ajoute le probe id au début
	unshift(@rows, $probe_id);

	# On affiche
	print join("\t", @rows) . "\n";

}
